### ISSUE TITLE
Bayesian Filter - seeming dependence on previous scan

### ISSUE THREAD

**Issue by alexberndt** [ernstmul/SmarphoneSensing#4]
The Bayesian filter seems to work perfectly (locates the current cell), however, it takes 5-6 scans before it actually gets the current cell. It seems to have some form of dependence on the previous cell.

Possible solutions:
* do multiple scans before real scan

**Comment by ernstmul** [comment]
Fixed by doing multiple (10) scans, and only use the last 5 of them.
